---
- name: configure EC2 with docker and kubernetes
  hosts: all
  become: yes
  tasks:

    - name: update the system
      yum:
        name: '*'
        state: latest

    - name: install docker
      yum:
        name: docker
        state: present

    - name: start and enable docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: add EC2 user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: install k3s dependencies
      yum:
        name:
          - curl
          - gettext
        state: present

    - name: install AWS CLI
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install
      args:
        creates: /usr/local/bin/aws

    - name: install k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: allow ec2-user to use kubectl
      file:
        path: /etc/rancher/k3s/k3s.yaml
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: set KUBECONFIG for ec2-user
      lineinfile:
        path: /home/ec2-user/.bashrc
        line: 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml'
        state: present

    - name: create kubectl symlink
      file:
        src: /usr/local/bin/k3s
        dest: /usr/local/bin/kubectl
        state: link
