apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs
        image: ${IMAGE}
        ports:
        - containerPort: 3000
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: peso-secrets
                  key: DATABASE_HOST
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: peso-secrets
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: peso-secrets
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: peso-secrets
                  key: DATABASE_PASSWORD
            - name: PUBLIC_IP
              valueFrom:
                secretKeyRef:
                  name: peso-secrets
                  key: PUBLIC_IP
            - name: AUTH_GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: peso-secrets
                  key: AUTH_GOOGLE_ID
            - name: AUTH_GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: peso-secrets
                  key: AUTH_GOOGLE_SECRET
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: peso-secrets
                  key: AUTH_SECRET
            - name: AUTH_TRUST_HOST
              valueFrom:
                secretKeyRef:
                  name: peso-secrets
                  key: AUTH_TRUST_HOST
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        image: ${NGINX_IMAGE}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-secret
