apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs
        image: 072216710152.dkr.ecr.sa-east-1.amazonaws.com/peso-repo:nextjs-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DATABASE_URL
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DATABASE_HOST
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DATABASE_NAME
        - name: NEXTAUTH_URL
          value: "https://pesodevops.com"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: NEXTAUTH_SECRET
        - name: AUTH_GOOGLE_ID
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: AUTH_GOOGLE_ID
        - name: AUTH_GOOGLE_SECRET
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: AUTH_GOOGLE_SECRET
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: AUTH_SECRET
        - name: AUTH_TRUST_HOST
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: AUTH_TRUST_HOST

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        image: 072216710152.dkr.ecr.sa-east-1.amazonaws.com/peso-repo:nginx-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: ClusterIP
  selector:
    app: nextjs-app
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: arthur.moreira.1995@hotmail.com
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      - http01:
          ingress:
            class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pesodevops-com-cert
spec:
  secretName: pesodevops-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: pesodevops.com
  dnsNames:
    - pesodevops.com
    - www.pesodevops.com

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pesodevops-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pesodevops.com
        - www.pesodevops.com
      secretName: pesodevops-tls
  rules:
    - host: pesodevops.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-service
                port:
                  number: 3000
