apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs
        image: peso-nextjs:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DATABASE_URL
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DATABASE_HOST
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DATABASE_NAME
        - name: NEXTAUTH_URL
          value: "https://pesodevops.com"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: NEXTAUTH_SECRET
        - name: AUTH_GOOGLE_ID
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: AUTH_GOOGLE_ID
        - name: AUTH_GOOGLE_SECRET
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: AUTH_GOOGLE_SECRET
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: AUTH_SECRET
        - name: AUTH_TRUST_HOST
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: AUTH_TRUST_HOST

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      volumes:
        - name: certs
          emptyDir: {}

      initContainers:
        - name: certbot
          image: certbot/certbot:latest
          args: ["certonly", "--standalone", "--agree-tos", "--register-unsafely-without-email", "-d", "pesodevops.com", "-d", "www.pesodevops.com", "--non-interactive"]
          volumeMounts:
            - mountPath: "/etc/letsencrypt"
              name: certs

      containers:
      - name: nginx
        image: peso-nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - mountPath: "/etc/letsencrypt"
            name: certs

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort
  selector:
    app: nextjs-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31234

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-proxy
  ports:
  - port: 80
    targetPort: 80
  - port: 443
    targetPort: 443
  type: LoadBalancer
