apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs
        image: peso-nextjs:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/$(DB_NAME)"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: DB_NAME
        - name: NEXTAUTH_URL
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: NEXTAUTH_URL
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: NEXTAUTH_SECRET
        - name: AUTH_GOOGLE_ID
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: AUTH_GOOGLE_ID
        - name: AUTH_GOOGLE_SECRET
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: AUTH_GOOGLE_SECRET
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: AUTH_SECRET
        - name: AUTH_TRUST_HOST
          valueFrom:
            secretKeyRef:
              name: peso-secrets
              key: AUTH_TRUST_HOST

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        image: peso-nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs-app
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-proxy
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
